/// 应用界面文字多语言支持
/// 定义所有界面文字的多语言版本
class AppStrings {
  // 当前语言（默认为中文）
  static String currentLanguage = 'zh';

  // 所有语言文字映射
  static const Map<String, Map<String, String>> _strings = {
    'it': {
      // 首页
      'app_title': 'Patente Italia',
      'select_mode': 'Seleziona Modalità',
      'start_practice': 'Quiz per Argomento',
      'mock_test': 'Simulazione Esame',
      'mistake_review': 'Ripasso Errori',
      'settings': 'Impostazioni',
      'select_chapter': 'Seleziona Capitolo',
      
      // 练习模式
      'practice_mode_title': 'Modalità Esercitazione',
      'questions_answered': 'Risposte',
      'errors': 'Errori',
      'question_id': 'ID Domanda',
      'correct': 'Corretto',
      'wrong': 'Errato',
      'show_explanation': 'Mostra Spiegazione',
      'hide_explanation': 'Nascondi Spiegazione',
      'translation': 'Traduzione',
      'show_translation': 'Traduzione',
      'hide_translation': 'Nascondi Traduzione',
      'correct_answer': 'Corretto!',
      'wrong_answer': 'Errato :(',
      'question_mastered': 'Domanda Padroneggiata!',
      'favorite': 'Preferiti',
      'unfavorite': 'Rimuovi dai Preferiti',
      'favorited': 'Aggiunto ai Preferiti',
      'unfavorited': 'Rimosso dai Preferiti',
      
      // 模拟考试
      'mock_test_title': 'Simulazione Esame',
      'time_remaining': 'Tempo Rimanente',
      'question': 'Domanda',
      'of': 'di',
      'mock_test_completed': 'Simulazione Completata!',
      'test_result': 'Risultato Esame',
      'result': 'Risultato',
      'passed': 'Superato',
      'failed': 'Non Superato',
      'idoneo': 'IDONEO',
      'non_idoneo': 'NON IDONEO',
      'error_distribution': 'Distribuzione degli Errori',
      'errors_in_chapter': 'errori',
      'targeted_review': 'Ripasso Mirato',
      'view_test_errors': 'Visualizza Errori del Test',
      'no_chapter_errors': 'Nessun errore per capitolo',
      'correct_answers': 'Risposte Corrette',
      'error_count': 'Errori',
      'max_allowed': 'Massimo Consentito',
      'time_up': 'Tempo Scaduto',
      'restart': 'Ricomincia',
      'return_to_practice': 'Torna alla Pratica',
      'return_home': 'Torna alla Home',
      
      // 设置页面
      'settings_title': 'Impostazioni',
      'language': 'Lingua',
      'premium_status': 'Stato Premium',
      'premium_user': 'Utente Premium',
      'free_user': 'Utente Gratuito',
      'about': 'Informazioni',
      'version': 'Versione',
      'select_language': 'Seleziona Lingua',
      
      // 会员页面
      'upgrade_premium': 'Aggiorna a Premium',
      'upgrade_to_premium': 'Aggiorna a Premium',
      'unlock_all_chapters': 'Sblocca Tutti i Capitoli',
      'ad_free_experience': 'Esperienza Senza Pubblicità',
      'cloud_sync': 'Sincronizzazione Cloud',
      'detailed_stats': 'Statistiche Dettagliate',
      'subscribe_now': 'Abbonati Ora',
      'restore_purchase': 'Ripristina Acquisto',
      'upgraded_to_premium': 'Aggiornato a Premium (Modalità Demo)',
      'restore_purchase_demo': 'Ripristina Acquisto (Modalità Demo)',
      
      // 通用
      'confirm': 'Conferma',
      'cancel': 'Annulla',
      'retry': 'Riprova',
      'close': 'Chiudi',
      'loading': 'Caricamento...',
      'failed_to_load': 'Caricamento Fallito',
      'failed_to_load_question': 'Impossibile Caricare la Domanda',
      'no_questions_in_chapter': 'Nessuna domanda disponibile in questo capitolo',
      'question_content_missing': 'Contenuto Domanda Mancante',
      'image_load_failed': 'Impossibile Caricare Immagine',
      'database_init_failed': 'Inizializzazione Database Fallita, Alcune Funzionalità Potrebbero Non Essere Disponibili',
      'database_init_success': 'Database Inizializzato con Successo!',
      'retry_failed': 'Tentativo Fallito',
      'answered': 'Risposte',
      'cannot_load_question': 'Impossibile Caricare la Domanda',
      'load_question_failed': 'Caricamento Domanda Fallito',
      'explanation_missing': 'Spiegazione Mancante',
      'cannot_get_enough_questions': 'Impossibile Ottenere Domande Sufficienti',
      'start_mock_test_failed': 'Avvio Simulazione Fallito',
      'test_completed': 'Esame Completato',
      'total_questions': 'Domande Totali',
      'incorrect_questions': 'Domande Errate',
      'restart_test': 'Ricomincia Esame',
      'cancel_favorite': 'Rimosso dai Preferiti',
      'add_favorite': 'Aggiunto ai Preferiti',
      'upgrade_premium_title': 'Aggiorna a Premium',
      'demo_mode': 'Modalità Demo',
      'no_mistakes': 'Nessun errore registrato',
      'all_questions_mastered': 'Congratulazioni! Hai padroneggiato tutte le domande in questa modalità.',
      'review_mastered': 'Rivedi Domande Padroneggiate',
      'study_progress': 'Progressi',
      'questions_answered_label': 'Quiz completati',
      'mastered_label': 'Padroneggiate',
      'best_mock_test_score': 'Miglior punteggio',
      'no_score_yet': 'Nessun risultato',
      'random_practice': 'Quiz Casuali',
      'skip_mastered_questions': 'Salta domande padroneggiate',
      'chapter_practice': 'Quiz per Argomento',
      'official_mock_test': 'Esame Ufficiale',
      'favorite_questions': 'Preferiti',
      'no_favorites': 'Nessuna domanda preferita',
      'other_features': 'Altre Funzionalità',
      'no_chapters': 'Nessun capitolo disponibile',
    },
    
    'zh': {
      // 首页
      'app_title': '意大利驾照测验',
      'select_mode': '选择模式',
      'start_practice': '刷题模式',
      'mock_test': '模拟考试',
      'mistake_review': '错题回顾',
      'settings': '设置',
      'select_chapter': '选择章节',
      
      // 练习模式
      'practice_mode_title': '练习模式',
      'questions_answered': '答题',
      'errors': '错误',
      'question_id': '题目 ID',
      'correct': '正确',
      'wrong': '错误',
      'show_explanation': '显示解析',
      'hide_explanation': '隐藏解析',
      'translation': '翻译',
      'show_translation': '翻译',
      'hide_translation': '隐藏翻译',
      'correct_answer': '正确！',
      'wrong_answer': '错误 :(',
      'question_mastered': '已掌握该题！',
      'favorite': '收藏',
      'unfavorite': '取消收藏',
      'favorited': '已收藏',
      'unfavorited': '已取消收藏',
      
      // 模拟考试
      'mock_test_title': '模拟考试',
      'time_remaining': '剩余时间',
      'question': '题目',
      'of': '共',
      'mock_test_completed': '模拟考试完成！',
      'test_result': '考试结果',
      'result': '结果',
      'passed': '及格',
      'failed': '不及格',
      'idoneo': 'IDONEO',
      'non_idoneo': 'NON IDONEO',
      'error_distribution': '错误分布分析',
      'errors_in_chapter': '处错误',
      'targeted_review': '针对性复习',
      'view_test_errors': '查看本套试卷错题',
      'no_chapter_errors': '无章节错误',
      'correct_answers': '正确答案',
      'error_count': '错误题数',
      'max_allowed': '最多允许',
      'time_up': '时间已到',
      'restart': '重新开始',
      'return_to_practice': '返回练习',
      'return_home': '返回首页',
      
      // 设置页面
      'settings_title': '设置',
      'language': '语言',
      'premium_status': '会员状态',
      'premium_user': '付费会员',
      'free_user': '免费用户',
      'about': '关于',
      'version': '版本',
      'select_language': '选择语言',
      
      // 会员页面
      'upgrade_premium': '升级会员',
      'upgrade_to_premium': '升级为付费会员',
      'unlock_all_chapters': '解锁所有章节',
      'ad_free_experience': '无广告体验',
      'cloud_sync': '云端同步进度',
      'detailed_stats': '详细学习统计',
      'subscribe_now': '立即订阅',
      'restore_purchase': '恢复购买',
      'upgraded_to_premium': '已升级为付费会员（演示模式）',
      'restore_purchase_demo': '恢复购买功能（演示模式）',
      
      // 通用
      'confirm': '确定',
      'cancel': '取消',
      'retry': '重试',
      'close': '关闭',
      'loading': '加载中...',
      'failed_to_load': '加载失败',
      'failed_to_load_question': '无法加载题目',
      'no_questions_in_chapter': '该章节暂无题目，请稍后再试',
      'question_content_missing': '题目内容缺失',
      'image_load_failed': '图片无法加载',
      'database_init_failed': '数据库初始化失败，部分功能可能无法使用',
      'database_init_success': '数据库初始化成功！',
      'retry_failed': '重试失败',
      'answered': '答题',
      'cannot_load_question': '无法加载题目',
      'load_question_failed': '加载题目失败',
      'explanation_missing': '解析内容缺失',
      'cannot_get_enough_questions': '无法获取足够的题目来开始模拟考试',
      'start_mock_test_failed': '开始模拟考试失败',
      'test_completed': '考试已完成',
      'total_questions': '总题数',
      'incorrect_questions': '错误题数',
      'restart_test': '重新开始',
      'cancel_favorite': '已取消收藏',
      'add_favorite': '已收藏',
      'upgrade_premium_title': '升级为付费会员',
      'demo_mode': '演示模式',
      'no_mistakes': '没有错题记录',
      'all_questions_mastered': '恭喜！当前模式下的题目已全部掌握。',
      'review_mastered': '重温已掌握',
      'study_progress': '学习进度',
      'questions_answered_label': '已答题目',
      'mastered_label': '已掌握',
      'best_mock_test_score': '最高成绩',
      'no_score_yet': '暂无成绩',
      'random_practice': '随机刷题',
      'skip_mastered_questions': '跳过已掌握题目',
      'chapter_practice': '章节练习',
      'official_mock_test': '模拟考试',
      'favorite_questions': '我的收藏',
      'other_features': '其他功能',
      'no_chapters': '暂无章节',
    },
    
    'en': {
      // Home
      'app_title': 'Italy Driving License Quiz',
      'select_mode': 'Select Mode',
      'start_practice': 'Quiz Practice',
      'mock_test': 'Mock Test',
      'mistake_review': 'Review Mistakes',
      'settings': 'Settings',
      'select_chapter': 'Select Chapter',
      
      // Practice Mode
      'practice_mode_title': 'Practice Mode',
      'questions_answered': 'Answered',
      'errors': 'Errors',
      'question_id': 'Question ID',
      'correct': 'Correct',
      'wrong': 'Wrong',
      'show_explanation': 'Show Explanation',
      'hide_explanation': 'Hide Explanation',
      'translation': 'Translation',
      'show_translation': 'Translation',
      'hide_translation': 'Hide Translation',
      'correct_answer': 'Correct!',
      'wrong_answer': 'Wrong :(',
      'question_mastered': 'Question Mastered!',
      'favorite': 'Favorite',
      'unfavorite': 'Unfavorite',
      'favorited': 'Favorited',
      'unfavorited': 'Unfavorited',
      
      // Mock Test
      'mock_test_title': 'Mock Test',
      'time_remaining': 'Time Remaining',
      'question': 'Question',
      'of': 'of',
      'mock_test_completed': 'Mock Test Completed!',
      'test_result': 'Test Result',
      'result': 'Result',
      'passed': 'Passed',
      'failed': 'Failed',
      'idoneo': 'IDONEO',
      'non_idoneo': 'NON IDONEO',
      'error_distribution': 'Error Distribution',
      'errors_in_chapter': 'errors',
      'targeted_review': 'Targeted Review',
      'view_test_errors': 'View Test Errors',
      'no_chapter_errors': 'No chapter errors',
      'correct_answers': 'Correct Answers',
      'error_count': 'Errors',
      'max_allowed': 'Max Allowed',
      'time_up': 'Time\'s Up',
      'restart': 'Restart',
      'return_to_practice': 'Return to Practice',
      'return_home': 'Return Home',
      
      // Settings
      'settings_title': 'Settings',
      'language': 'Language',
      'premium_status': 'Premium Status',
      'premium_user': 'Premium User',
      'free_user': 'Free User',
      'about': 'About',
      'version': 'Version',
      'select_language': 'Select Language',
      
      // Premium
      'upgrade_premium': 'Upgrade Premium',
      'upgrade_to_premium': 'Upgrade to Premium',
      'unlock_all_chapters': 'Unlock All Chapters',
      'ad_free_experience': 'Ad-Free Experience',
      'cloud_sync': 'Cloud Sync Progress',
      'detailed_stats': 'Detailed Learning Statistics',
      'subscribe_now': 'Subscribe Now',
      'restore_purchase': 'Restore Purchase',
      'upgraded_to_premium': 'Upgraded to Premium (Demo Mode)',
      'restore_purchase_demo': 'Restore Purchase (Demo Mode)',
      
      // Common
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'retry': 'Retry',
      'close': 'Close',
      'loading': 'Loading...',
      'failed_to_load': 'Failed to Load',
      'failed_to_load_question': 'Failed to Load Question',
      'no_questions_in_chapter': 'No questions available in this chapter',
      'question_content_missing': 'Question Content Missing',
      'image_load_failed': 'Image Load Failed',
      'database_init_failed': 'Database initialization failed, some features may be unavailable',
      'database_init_success': 'Database initialization successful!',
      'retry_failed': 'Retry Failed',
      'answered': 'Answered',
      'cannot_load_question': 'Cannot load question',
      'load_question_failed': 'Failed to load question',
      'explanation_missing': 'Explanation missing',
      'cannot_get_enough_questions': 'Cannot get enough questions for mock test',
      'start_mock_test_failed': 'Failed to start mock test',
      'test_completed': 'Test Completed',
      'total_questions': 'Total Questions',
      'incorrect_questions': 'Incorrect Questions',
      'restart_test': 'Restart Test',
      'cancel_favorite': 'Unfavorited',
      'add_favorite': 'Favorited',
      'upgrade_premium_title': 'Upgrade to Premium Member',
      'demo_mode': 'Demo Mode',
      'no_mistakes': 'No mistakes recorded',
      'all_questions_mastered': 'Congratulations! You have mastered all questions in this mode.',
      'review_mastered': 'Review Mastered Questions',
      'study_progress': 'Study Progress',
      'questions_answered_label': 'Questions Done',
      'mastered_label': 'Mastered',
      'best_mock_test_score': 'Best Score',
      'no_score_yet': 'No score yet',
      'random_practice': 'Random Quiz',
      'skip_mastered_questions': 'Skip Mastered Questions',
      'chapter_practice': 'Chapter Practice',
      'official_mock_test': 'Mock Exam',
      'favorite_questions': 'Favorites',
      'no_favorites': 'No favorite questions',
      'other_features': 'Other Features',
      'no_chapters': 'No chapters available',
    },
    
    'ru': {
      // Главная
      'app_title': 'Тест на итальянские водительские права',
      'select_mode': 'Выберите режим',
      'start_practice': 'Практика',
      'mock_test': 'Пробный тест',
      'mistake_review': 'Работа над ошибками',
      'settings': 'Настройки',
      
      // Режим практики
      'practice_mode_title': 'Режим практики',
      'questions_answered': 'Отвечено',
      'errors': 'Ошибки',
      'question_id': 'ID вопроса',
      'correct': 'Правильно',
      'wrong': 'Неправильно',
      'show_explanation': 'Показать объяснение',
      'hide_explanation': 'Скрыть объяснение',
      'translation': 'Перевод',
      'show_translation': 'Перевод',
      'hide_translation': 'Скрыть перевод',
      'correct_answer': 'Правильно!',
      'wrong_answer': 'Неправильно :(',
      'question_mastered': 'Вопрос освоен!',
      'favorite': 'Избранное',
      'unfavorite': 'Удалить из избранного',
      'favorited': 'Добавлено в избранное',
      'unfavorited': 'Удалено из избранного',
      
      // Пробный тест
      'mock_test_title': 'Пробный тест',
      'time_remaining': 'Осталось времени',
      'question': 'Вопрос',
      'of': 'из',
      'mock_test_completed': 'Пробный тест завершен!',
      'test_result': 'Результат теста',
      'result': 'Результат',
      'passed': 'Сдан',
      'failed': 'Не сдан',
      'idoneo': 'IDONEO',
      'non_idoneo': 'NON IDONEO',
      'error_distribution': 'Распределение ошибок',
      'errors_in_chapter': 'ошибок',
      'targeted_review': 'Целевой обзор',
      'view_test_errors': 'Просмотр ошибок теста',
      'no_chapter_errors': 'Нет ошибок по главам',
      'correct_answers': 'Правильных ответов',
      'error_count': 'Ошибок',
      'max_allowed': 'Максимум разрешено',
      'time_up': 'Время вышло',
      'restart': 'Начать заново',
      'return_to_practice': 'Вернуться к практике',
      'return_home': 'Вернуться на главную',
      
      // Настройки
      'settings_title': 'Настройки',
      'language': 'Язык',
      'premium_status': 'Статус премиум',
      'premium_user': 'Премиум пользователь',
      'free_user': 'Бесплатный пользователь',
      'about': 'О приложении',
      'version': 'Версия',
      'select_language': 'Выберите язык',
      
      // Премиум
      'upgrade_premium': 'Обновить до премиум',
      'upgrade_to_premium': 'Обновить до премиум',
      'unlock_all_chapters': 'Разблокировать все главы',
      'ad_free_experience': 'Без рекламы',
      'cloud_sync': 'Синхронизация в облаке',
      'detailed_stats': 'Подробная статистика обучения',
      'subscribe_now': 'Подписаться сейчас',
      'restore_purchase': 'Восстановить покупку',
      'upgraded_to_premium': 'Обновлено до премиум (демо режим)',
      'restore_purchase_demo': 'Восстановить покупку (демо режим)',
      
      // Общее
      'confirm': 'Подтвердить',
      'cancel': 'Отмена',
      'retry': 'Повторить',
      'close': 'Закрыть',
      'loading': 'Загрузка...',
      'failed_to_load': 'Не удалось загрузить',
      'failed_to_load_question': 'Не удалось загрузить вопрос',
      'no_questions_in_chapter': 'Нет вопросов в этой главе',
      'question_content_missing': 'Содержание вопроса отсутствует',
      'image_load_failed': 'Не удалось загрузить изображение',
      'database_init_failed': 'Инициализация базы данных не удалась, некоторые функции могут быть недоступны',
      'database_init_success': 'Инициализация базы данных успешна!',
      'retry_failed': 'Повтор не удался',
      'answered': 'Отвечено',
      'cannot_load_question': 'Невозможно загрузить вопрос',
      'load_question_failed': 'Не удалось загрузить вопрос',
      'explanation_missing': 'Объяснение отсутствует',
      'cannot_get_enough_questions': 'Невозможно получить достаточно вопросов для пробного теста',
      'start_mock_test_failed': 'Не удалось начать пробный тест',
      'test_completed': 'Тест завершен',
      'total_questions': 'Всего вопросов',
      'incorrect_questions': 'Неправильные вопросы',
      'restart_test': 'Начать заново',
      'cancel_favorite': 'Удалено из избранного',
      'add_favorite': 'Добавлено в избранное',
      'upgrade_premium_title': 'Обновить до премиум-члена',
      'demo_mode': 'Демо режим',
      'no_mistakes': 'Ошибок не зарегистрировано',
      'all_questions_mastered': 'Поздравляем! Вы освоили все вопросы в этом режиме.',
      'review_mastered': 'Повторить Освоенные Вопросы',
      'study_progress': 'Прогресс',
      'questions_answered_label': 'Решено задач',
      'mastered_label': 'Освоено',
      'best_mock_test_score': 'Лучший результат',
      'no_score_yet': 'Нет результата',
      'random_practice': 'Случайные тесты',
      'skip_mastered_questions': 'Пропустить освоенные вопросы',
      'chapter_practice': 'Тесты по главам',
      'official_mock_test': 'Экзамен',
      'favorite_questions': 'Избранное',
      'other_features': 'Другие функции',
      'no_chapters': 'Нет доступных глав',
    },
    
    'ur': {
      // 首页
      'app_title': 'اٹلی ڈرائیونگ لائسنس',
      'select_mode': 'موڈ منتخب کریں',
      'start_practice': 'سوالات کی مشق',
      'mock_test': 'فرضی ٹیسٹ',
      'mistake_review': 'غلطیوں کا جائزہ',
      'settings': 'ترتیبات',
      'select_chapter': 'باب منتخب کریں',
      
      // 练习模式
      'practice_mode_title': 'مشق کا موڈ',
      'questions_answered': 'جواب دیا',
      'errors': 'غلطیاں',
      'question_id': 'سوال ID',
      'correct': 'درست',
      'wrong': 'غلط',
      'show_explanation': 'وضاحت دکھائیں',
      'hide_explanation': 'وضاحت چھپائیں',
      'translation': 'ترجمہ',
      'show_translation': 'ترجمہ',
      'hide_translation': 'ترجمہ چھپائیں',
      'correct_answer': 'درست!',
      'wrong_answer': 'غلط :(',
      'question_mastered': 'سوال میں مہارت حاصل کی!',
      'favorite': 'پسندیدہ',
      'unfavorite': 'پسندیدہ سے ہٹائیں',
      'favorited': 'پسندیدہ میں شامل',
      'unfavorited': 'پسندیدہ سے ہٹایا',
      
      // 模拟考试
      'mock_test_title': 'فرضی ٹیسٹ',
      'time_remaining': 'بقیہ وقت',
      'question': 'سوال',
      'of': 'کا',
      'mock_test_completed': 'فرضی ٹیسٹ مکمل!',
      'test_result': 'ٹیسٹ کا نتیجہ',
      'result': 'نتیجہ',
      'passed': 'پاس',
      'failed': 'فیل',
      'idoneo': 'IDONEO',
      'non_idoneo': 'NON IDONEO',
      'error_distribution': 'غلطیوں کی تقسیم',
      'errors_in_chapter': 'غلطیاں',
      'targeted_review': 'ہدفی جائزہ',
      'view_test_errors': 'ٹیسٹ کی غلطیاں دیکھیں',
      'no_chapter_errors': 'باب میں کوئی غلطی نہیں',
      'correct_answers': 'درست جوابات',
      'error_count': 'غلطیاں',
      'max_allowed': 'زیادہ سے زیادہ اجازت',
      'time_up': 'وقت ختم!',
      'restart': 'دوبارہ شروع',
      'return_to_practice': 'مشق پر واپس',
      'return_home': 'ہوم پر واپس',
      
      // 设置页面
      'settings_title': 'ترتیبات',
      'language': 'زبان',
      'premium_status': 'پریمیم کی حیثیت',
      'premium_user': 'پریمیم صارف',
      'free_user': 'مفت صارف',
      'about': 'کے بارے میں',
      'version': 'ورژن',
      'select_language': 'زبان منتخب کریں',
      
      // 会员页面
      'upgrade_premium': 'پریمیم اپ گریڈ',
      'upgrade_to_premium': 'پریمیم میں اپ گریڈ',
      'unlock_all_chapters': 'تمام ابواب کھولیں',
      'ad_free_experience': 'اشتہار سے پاک تجربہ',
      'cloud_sync': 'کلاؤڈ سینک',
      'detailed_stats': 'تفصیلی اعداد و شمار',
      'subscribe_now': 'اب سبسکرائب کریں',
      'restore_purchase': 'خریداری بحال کریں',
      'upgraded_to_premium': 'پریمیم میں اپ گریڈ (ڈیمو موڈ)',
      'restore_purchase_demo': 'خریداری بحال (ڈیمو موڈ)',
      
      // 通用
      'confirm': 'تصدیق',
      'cancel': 'منسوخ',
      'retry': 'دوبارہ کوشش',
      'close': 'بند کریں',
      'loading': 'لوڈ ہو رہا ہے...',
      'failed_to_load': 'لوڈ ناکام',
      'failed_to_load_question': 'سوال لوڈ نہیں ہو سکا',
      'no_questions_in_chapter': 'اس باب میں کوئی سوال دستیاب نہیں',
      'question_content_missing': 'سوال کا مواد غائب',
      'image_load_failed': 'تصویر لوڈ نہیں ہو سکی',
      'database_init_failed': 'ڈیٹا بیس کی ابتدا ناکام، کچھ خصوصیات دستیاب نہیں ہو سکتیں',
      'database_init_success': 'ڈیٹا بیس کامیابی سے شروع ہوا!',
      'retry_failed': 'دوبارہ کوشش ناکام',
      'answered': 'جواب دیا',
      'cannot_load_question': 'سوال لوڈ نہیں کر سکتا',
      'load_question_failed': 'سوال لوڈ کرنے میں ناکام',
      'explanation_missing': 'وضاحت غائب',
      'cannot_get_enough_questions': 'فرضی ٹیسٹ کے لیے کافی سوالات نہیں مل سکے',
      'start_mock_test_failed': 'فرضی ٹیسٹ شروع کرنے میں ناکام',
      'test_completed': 'ٹیسٹ مکمل',
      'total_questions': 'کل سوالات',
      'incorrect_questions': 'غلط سوالات',
      'restart_test': 'ٹیسٹ دوبارہ شروع',
      'cancel_favorite': 'پسندیدہ سے ہٹایا',
      'add_favorite': 'پسندیدہ میں شامل',
      'upgrade_premium_title': 'پریمیم ممبر میں اپ گریڈ',
      'demo_mode': 'ڈیمو موڈ',
      'no_mistakes': 'کوئی غلطی ریکارڈ نہیں',
      'all_questions_mastered': 'مبارک ہو! آپ نے اس موڈ میں تمام سوالات میں مہارت حاصل کر لی ہے۔',
      'review_mastered': 'مہارت یافتہ سوالات کا جائزہ لیں',
      'study_progress': 'سیکھنے کی پیشرفت',
      'questions_answered_label': 'حل شدہ سوالات',
      'mastered_label': 'مہارت حاصل',
      'best_mock_test_score': 'بہترین سکور',
      'no_score_yet': 'ابھی تک کوئی سکور نہیں',
      'random_practice': 'بے ترتیب کوئز',
      'skip_mastered_questions': 'مہارت یافتہ سوالات کو چھوڑیں',
      'chapter_practice': 'باب کی مشق',
      'official_mock_test': 'فرضی امتحان',
      'favorite_questions': 'پسندیدہ',
      'no_favorites': 'کوئی پسندیدہ سوال نہیں',
      'other_features': 'دیگر خصوصیات',
      'no_chapters': 'کوئی باب دستیاب نہیں',
    },
    
    'pa': {
      // 首页
      'app_title': 'ਇਟਲੀ ਡਰਾਈਵਿੰਗ ਲਾਇਸੈਂਸ',
      'select_mode': 'ਮੋਡ ਚੁਣੋ',
      'start_practice': 'ਸਵਾਲਾਂ ਦਾ ਅਭਿਆਸ',
      'mock_test': 'ਮੌਕ ਟੈਸਟ',
      'mistake_review': 'ਗਲਤੀਆਂ ਦੀ ਸਮੀਖਿਆ',
      'settings': 'ਸੈਟਿੰਗਾਂ',
      'select_chapter': 'ਅਧਿਆਇ ਚੁਣੋ',
      
      // 练习模式
      'practice_mode_title': 'ਅਭਿਆਸ ਮੋਡ',
      'questions_answered': 'ਜਵਾਬ ਦਿੱਤਾ',
      'errors': 'ਗਲਤੀਆਂ',
      'question_id': 'ਸਵਾਲ ID',
      'correct': 'ਸਹੀ',
      'wrong': 'ਗਲਤ',
      'show_explanation': 'ਸਮਝਾਓ ਦਿਖਾਓ',
      'hide_explanation': 'ਸਮਝਾਓ ਲੁਕਾਓ',
      'translation': 'ਅਨੁਵਾਦ',
      'show_translation': 'ਅਨੁਵਾਦ',
      'hide_translation': 'ਅਨੁਵਾਦ ਲੁਕਾਓ',
      'correct_answer': 'ਸਹੀ!',
      'wrong_answer': 'ਗਲਤ :(',
      'question_mastered': 'ਸਵਾਲ ਵਿੱਚ ਮਾਹਰ!',
      'favorite': 'ਪਸੰਦੀਦਾ',
      'unfavorite': 'ਪਸੰਦੀਦਾ ਤੋਂ ਹਟਾਓ',
      'favorited': 'ਪਸੰਦੀਦਾ ਵਿੱਚ ਸ਼ਾਮਿਲ',
      'unfavorited': 'ਪਸੰਦੀਦਾ ਤੋਂ ਹਟਾਇਆ',
      
      // 模拟考试
      'mock_test_title': 'ਮੌਕ ਟੈਸਟ',
      'time_remaining': 'ਬਾਕੀ ਸਮਾਂ',
      'question': 'ਸਵਾਲ',
      'of': 'ਦਾ',
      'mock_test_completed': 'ਮੌਕ ਟੈਸਟ ਪੂਰਾ!',
      'test_result': 'ਟੈਸਟ ਦਾ ਨਤੀਜਾ',
      'result': 'ਨਤੀਜਾ',
      'passed': 'ਪਾਸ',
      'failed': 'ਫੇਲ',
      'idoneo': 'IDONEO',
      'non_idoneo': 'NON IDONEO',
      'error_distribution': 'ਗਲਤੀਆਂ ਦੀ ਵੰਡ',
      'errors_in_chapter': 'ਗਲਤੀਆਂ',
      'targeted_review': 'ਟੀਚੇਬੱਧ ਸਮੀਖਿਆ',
      'view_test_errors': 'ਟੈਸਟ ਗਲਤੀਆਂ ਵੇਖੋ',
      'no_chapter_errors': 'ਅਧਿਆਇ ਵਿੱਚ ਕੋਈ ਗਲਤੀ ਨਹੀਂ',
      'correct_answers': 'ਸਹੀ ਜਵਾਬ',
      'error_count': 'ਗਲਤੀਆਂ',
      'max_allowed': 'ਅਧਿਕਤਮ ਮਨਜ਼ੂਰ',
      'time_up': 'ਸਮਾਂ ਖਤਮ!',
      'restart': 'ਦੁਬਾਰਾ ਸ਼ੁਰੂ',
      'return_to_practice': 'ਅਭਿਆਸ ਤੇ ਵਾਪਸ',
      'return_home': 'ਘਰ ਤੇ ਵਾਪਸ',
      
      // 设置页面
      'settings_title': 'ਸੈਟਿੰਗਾਂ',
      'language': 'ਭਾਸ਼ਾ',
      'premium_status': 'ਪ੍ਰੀਮੀਅਮ ਸਥਿਤੀ',
      'premium_user': 'ਪ੍ਰੀਮੀਅਮ ਉਪਭੋਗਤਾ',
      'free_user': 'ਮੁਫ਼ਤ ਉਪਭੋਗਤਾ',
      'about': 'ਬਾਰੇ',
      'version': 'ਵਰਜਨ',
      'select_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      
      // 会员页面
      'upgrade_premium': 'ਪ੍ਰੀਮੀਅਮ ਅਪਗ੍ਰੇਡ',
      'upgrade_to_premium': 'ਪ੍ਰੀਮੀਅਮ ਵਿੱਚ ਅਪਗ੍ਰੇਡ',
      'unlock_all_chapters': 'ਸਭ ਅਧਿਆਏ ਖੋਲ੍ਹੋ',
      'ad_free_experience': 'ਵਿਗਿਆਪਨ-ਮੁਕਤ ਅਨੁਭਵ',
      'cloud_sync': 'ਕਲਾਉਡ ਸਿੰਕ',
      'detailed_stats': 'ਵਿਸਤ੍ਰਿਤ ਅੰਕੜੇ',
      'subscribe_now': 'ਹੁਣ ਸਬਸਕ੍ਰਾਈਬ ਕਰੋ',
      'restore_purchase': 'ਖਰੀਦ ਬਹਾਲ ਕਰੋ',
      'upgraded_to_premium': 'ਪ੍ਰੀਮੀਅਮ ਵਿੱਚ ਅਪਗ੍ਰੇਡ (ਡੈਮੋ ਮੋਡ)',
      'restore_purchase_demo': 'ਖਰੀਦ ਬਹਾਲ (ਡੈਮੋ ਮੋਡ)',
      
      // 通用
      'confirm': 'ਪੁਸ਼ਟੀ',
      'cancel': 'ਰੱਦ',
      'retry': 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼',
      'close': 'ਬੰਦ',
      'loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
      'failed_to_load': 'ਲੋਡ ਅਸਫਲ',
      'failed_to_load_question': 'ਸਵਾਲ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕਿਆ',
      'no_questions_in_chapter': 'ਇਸ ਅਧਿਆਇ ਵਿੱਚ ਕੋਈ ਸਵਾਲ ਉਪਲਬਧ ਨਹੀਂ',
      'question_content_missing': 'ਸਵਾਲ ਦੀ ਸਮੱਗਰੀ ਗਾਇਬ',
      'image_load_failed': 'ਚਿੱਤਰ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕਿਆ',
      'database_init_failed': 'ਡੇਟਾਬੇਸ ਸ਼ੁਰੂਆਤ ਅਸਫਲ, ਕੁਝ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ ਉਪਲਬਧ ਨਹੀਂ ਹੋ ਸਕਦੀਆਂ',
      'database_init_success': 'ਡੇਟਾਬੇਸ ਸਫਲਤਾਪੂਰਵਕ ਸ਼ੁਰੂ ਹੋਇਆ!',
      'retry_failed': 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਅਸਫਲ',
      'answered': 'ਜਵਾਬ ਦਿੱਤਾ',
      'cannot_load_question': 'ਸਵਾਲ ਲੋਡ ਨਹੀਂ ਕਰ ਸਕਦਾ',
      'load_question_failed': 'ਸਵਾਲ ਲੋਡ ਕਰਨ ਵਿੱਚ ਅਸਫਲ',
      'explanation_missing': 'ਸਮਝਾਓ ਗਾਇਬ',
      'cannot_get_enough_questions': 'ਮੌਕ ਟੈਸਟ ਲਈ ਕਾਫ਼ੀ ਸਵਾਲ ਨਹੀਂ ਮਿਲ ਸਕੇ',
      'start_mock_test_failed': 'ਮੌਕ ਟੈਸਟ ਸ਼ੁਰੂ ਕਰਨ ਵਿੱਚ ਅਸਫਲ',
      'test_completed': 'ਟੈਸਟ ਪੂਰਾ',
      'total_questions': 'ਕੁੱਲ ਸਵਾਲ',
      'incorrect_questions': 'ਗਲਤ ਸਵਾਲ',
      'restart_test': 'ਟੈਸਟ ਦੁਬਾਰਾ ਸ਼ੁਰੂ',
      'cancel_favorite': 'ਪਸੰਦੀਦਾ ਤੋਂ ਹਟਾਇਆ',
      'add_favorite': 'ਪਸੰਦੀਦਾ ਵਿੱਚ ਸ਼ਾਮਿਲ',
      'upgrade_premium_title': 'ਪ੍ਰੀਮੀਅਮ ਮੈਂਬਰ ਵਿੱਚ ਅਪਗ੍ਰੇਡ',
      'demo_mode': 'ਡੈਮੋ ਮੋਡ',
      'no_mistakes': 'ਕੋਈ ਗਲਤੀ ਰਿਕਾਰਡ ਨਹੀਂ',
      'all_questions_mastered': 'ਵਧਾਈਆਂ! ਤੁਸੀਂ ਇਸ ਮੋਡ ਵਿੱਚ ਸਾਰੇ ਸਵਾਲਾਂ ਵਿੱਚ ਮਾਹਰ ਹੋ ਗਏ ਹੋ।',
      'review_mastered': 'ਮਾਹਰ ਸਵਾਲਾਂ ਦੀ ਸਮੀਖਿਆ ਕਰੋ',
      'study_progress': 'ਸਿੱਖਣ ਦੀ ਤਰੱਕੀ',
      'questions_answered_label': 'ਜਵਾਬ ਦਿੱਤੇ ਸਵਾਲ',
      'mastered_label': 'ਮਾਹਰ',
      'best_mock_test_score': 'ਸਭ ਤੋਂ ਵਧੀਆ ਮੌਕ ਟੈਸਟ ਸਕੋਰ',
      'no_score_yet': 'ਅਜੇ ਤੱਕ ਕੋਈ ਸਕੋਰ ਨਹੀਂ',
      'random_practice': 'ਬੇਤਰਤੀਬ ਅਭਿਆਸ',
      'skip_mastered_questions': 'ਮਾਹਰ ਸਵਾਲਾਂ ਨੂੰ ਛੱਡੋ',
      'chapter_practice': 'ਅਧਿਆਇ ਅਭਿਆਸ',
      'official_mock_test': 'ਸਰਕਾਰੀ ਮੌਕ ਟੈਸਟ',
      'favorite_questions': 'ਪਸੰਦੀਦਾ ਸਵਾਲ',
      'no_favorites': 'ਕੋਈ ਪਸੰਦੀਦਾ ਸਵਾਲ ਨਹੀਂ',
      'other_features': 'ਹੋਰ ਫੀਚਰ',
      'no_chapters': 'ਕੋਈ ਅਧਿਆਇ ਉਪਲਬਧ ਨਹੀਂ',
    },
    
    'uk': {
      // Головна
      'app_title': 'Водійські права Італії',
      'select_mode': 'Виберіть режим',
      'start_practice': 'Тренування',
      'mock_test': 'Імітація іспиту',
      'mistake_review': 'Робота над помилками',
      'settings': 'Налаштування',
      'select_chapter': 'Виберіть розділ',
      
      // Режим практики
      'practice_mode_title': 'Режим практики',
      'questions_answered': 'Відповіли',
      'errors': 'Помилки',
      'question_id': 'ID питання',
      'correct': 'Правильно',
      'wrong': 'Неправильно',
      'show_explanation': 'Показати пояснення',
      'hide_explanation': 'Приховати пояснення',
      'translation': 'Переклад',
      'show_translation': 'Переклад',
      'hide_translation': 'Приховати переклад',
      'correct_answer': 'Правильно!',
      'wrong_answer': 'Неправильно :(',
      'question_mastered': 'Питання освоєно!',
      'favorite': 'Обране',
      'unfavorite': 'Прибрати з обраного',
      'favorited': 'Додано до обраного',
      'unfavorited': 'Прибрано з обраного',
      
      // Імітація іспиту
      'mock_test_title': 'Імітація іспиту',
      'time_remaining': 'Час, що залишився',
      'question': 'Питання',
      'of': 'з',
      'mock_test_completed': 'Імітація іспиту завершена!',
      'test_result': 'Результат тесту',
      'result': 'Результат',
      'passed': 'Складено',
      'failed': 'Не складено',
      'idoneo': 'IDONEO',
      'non_idoneo': 'NON IDONEO',
      'error_distribution': 'Розподіл помилок',
      'errors_in_chapter': 'помилок',
      'targeted_review': 'Цільовий огляд',
      'view_test_errors': 'Перегляд помилок тесту',
      'no_chapter_errors': 'Немає помилок за розділами',
      'correct_answers': 'Правильні відповіді',
      'error_count': 'Помилок',
      'max_allowed': 'Максимум дозволено',
      'time_up': 'Час вийшов!',
      'restart': 'Почати заново',
      'return_to_practice': 'Повернутися до практики',
      'return_home': 'Повернутися на головну',
      
      // Налаштування
      'settings_title': 'Налаштування',
      'language': 'Мова',
      'premium_status': 'Статус преміум',
      'premium_user': 'Преміум користувач',
      'free_user': 'Безкоштовний користувач',
      'about': 'Про додаток',
      'version': 'Версія',
      'select_language': 'Виберіть мову',
      
      // Преміум
      'upgrade_premium': 'Оновити до преміум',
      'upgrade_to_premium': 'Оновити до преміум',
      'unlock_all_chapters': 'Розблокувати всі розділи',
      'ad_free_experience': 'Без реклами',
      'cloud_sync': 'Синхронізація в хмарі',
      'detailed_stats': 'Детальна статистика навчання',
      'subscribe_now': 'Підписатися зараз',
      'restore_purchase': 'Відновити покупку',
      'upgraded_to_premium': 'Оновлено до преміум (демо режим)',
      'restore_purchase_demo': 'Відновити покупку (демо режим)',
      
      // Загальне
      'confirm': 'Підтвердити',
      'cancel': 'Скасувати',
      'retry': 'Повторити',
      'close': 'Закрити',
      'loading': 'Завантаження...',
      'failed_to_load': 'Не вдалося завантажити',
      'failed_to_load_question': 'Не вдалося завантажити питання',
      'no_questions_in_chapter': 'Немає питань у цьому розділі',
      'question_content_missing': 'Зміст питання відсутній',
      'image_load_failed': 'Не вдалося завантажити зображення',
      'database_init_failed': 'Ініціалізація бази даних не вдалася, деякі функції можуть бути недоступні',
      'database_init_success': 'База даних успішно ініціалізована!',
      'retry_failed': 'Повтор не вдався',
      'answered': 'Відповіли',
      'cannot_load_question': 'Неможливо завантажити питання',
      'load_question_failed': 'Не вдалося завантажити питання',
      'explanation_missing': 'Пояснення відсутнє',
      'cannot_get_enough_questions': 'Неможливо отримати достатньо питань для імітації іспиту',
      'start_mock_test_failed': 'Не вдалося розпочати імітацію іспиту',
      'test_completed': 'Тест завершено',
      'total_questions': 'Всього питань',
      'incorrect_questions': 'Неправильні питання',
      'restart_test': 'Почати тест заново',
      'cancel_favorite': 'Прибрано з обраного',
      'add_favorite': 'Додано до обраного',
      'upgrade_premium_title': 'Оновити до преміум-члена',
      'demo_mode': 'Демо режим',
      'no_mistakes': 'Помилок не зареєстровано',
      'all_questions_mastered': 'Вітаємо! Ви освоїли всі питання в цьому режимі.',
      'review_mastered': 'Повторити Освоєні Питання',
      'study_progress': 'Прогрес',
      'questions_answered_label': 'Вирішено питань',
      'mastered_label': 'Освоєно',
      'best_mock_test_score': 'Найкращий результат',
      'no_score_yet': 'Немає результату',
      'random_practice': 'Випадкові тести',
      'skip_mastered_questions': 'Пропустити освоєні питання',
      'chapter_practice': 'Тести за розділами',
      'official_mock_test': 'Імітація іспиту',
      'favorite_questions': 'Вибране',
      'other_features': 'Інші функції',
      'no_chapters': 'Немає доступних розділів',
    },
  };

  /// 获取指定键的文字（使用当前语言）
  static String get(String key) {
    return _strings[currentLanguage]?[key] ?? 
           _strings['zh']?[key] ?? 
           key; // 如果都找不到，返回键名本身
  }

  /// 获取指定语言和键的文字
  static String getWithLanguage(String language, String key) {
    return _strings[language]?[key] ?? 
           _strings['zh']?[key] ?? 
           key;
  }

  /// 设置当前语言
  static void setLanguage(String language) {
    if (_strings.containsKey(language)) {
      currentLanguage = language;
    }
  }

  /// 获取当前语言
  static String getLanguage() {
    return currentLanguage;
  }

  /// 获取所有支持的语言列表
  static List<String> getSupportedLanguages() {
    return _strings.keys.toList();
  }
}
